package com.personal.jz.common.exception;

import lombok.Getter;

@Getter
public enum ErrorCodeEnums {
    OK(0, "ok"),

    INVALID_USERNAME(10001, "INVALID_USERNAME"),
    WEAK_PASSWORD(10002, "WEAK_PASSWORD"),
    INVALID_CONTACT(10003, "INVALID_CONTACT"),
    PASSWORD_MISMATCH(10004, "PASSWORD_MISMATCH"),
    USERNAME_TAKEN(10005, "USERNAME_TAKEN"),
    INVALID_CREDENTIALS(10006, "INVALID_CREDENTIALS"),
    ACCOUNT_DISABLED(10007, "ACCOUNT_DISABLED"),
    ACCOUNT_LOCKED(10008, "ACCOUNT_LOCKED"),
    TOKEN_MISSING(10009, "TOKEN_MISSING"),
    TOKEN_EXPIRED(10010, "TOKEN_EXPIRED"),
    TOKEN_INVALID(10011, "TOKEN_INVALID"),
    TOKEN_REVOKED(10012, "TOKEN_REVOKED"),
    WRONG_OLD_PASSWORD(10013, "WRONG_OLD_PASSWORD"),
    SAME_PASSWORD(10014, "SAME_PASSWORD"),

    BOOK_NAME_TAKEN(20001, "BOOK_NAME_TAKEN"),
    BOOK_LIMIT_REACHED(20002, "BOOK_LIMIT_REACHED"),
    LAST_ACTIVE_BOOK(20003, "LAST_ACTIVE_BOOK"),
    BOOK_ARCHIVED(20004, "BOOK_ARCHIVED"),
    UNSUPPORTED_CURRENCY(20005, "UNSUPPORTED_CURRENCY"),

    CATEGORY_NOT_FOUND(30001, "CATEGORY_NOT_FOUND"),
    CATEGORY_TYPE_MISMATCH(30002, "CATEGORY_TYPE_MISMATCH"),
    CATEGORY_NAME_TAKEN(30003, "CATEGORY_NAME_TAKEN"),
    CATEGORY_LIMIT_REACHED(30004, "CATEGORY_LIMIT_REACHED"),
    SYSTEM_CATEGORY_READONLY(30005, "SYSTEM_CATEGORY_READONLY"),
    CATEGORY_IN_USE(30006, "CATEGORY_IN_USE"),

    INVALID_AMOUNT(40001, "INVALID_AMOUNT"),
    DATE_OUT_OF_RANGE(40002, "DATE_OUT_OF_RANGE"),
    TX_NOT_FOUND(40003, "TX_NOT_FOUND"),
    INVALID_PAY_METHOD(40004, "INVALID_PAY_METHOD"),

    INVALID_MONTH(50001, "INVALID_MONTH"),
    BUDGET_ON_INCOME(50002, "BUDGET_ON_INCOME"),

    FILE_TOO_LARGE(60001, "FILE_TOO_LARGE"),
    ROW_LIMIT(60002, "ROW_LIMIT"),
    UNSUPPORTED_FILE_TYPE(60003, "UNSUPPORTED_FILE_TYPE"),
    INVALID_HEADER(60004, "INVALID_HEADER"),
    FORMULA_INJECTION(60005, "FORMULA_INJECTION"),
    RANGE_TOO_LONG(60006, "RANGE_TOO_LONG"),

    PARAM_INVALID(70001, "PARAM_INVALID"),
    UNAUTHORIZED(70002, "UNAUTHORIZED"),
    FORBIDDEN(70003, "FORBIDDEN"),
    NOT_FOUND(70004, "NOT_FOUND"),
    CONFLICT(70005, "CONFLICT"),
    RATE_LIMITED(70006, "RATE_LIMITED"),
    INTERNAL_ERROR(70007, "INTERNAL_ERROR"),

    CANNOT_DISABLE_SELF(80001, "CANNOT_DISABLE_SELF"),
    TARGET_USER_NOT_FOUND(80002, "TARGET_USER_NOT_FOUND");

    private final int code;
    private final String msg;

    ErrorCodeEnums(int code, String msg) { this.code = code; this.msg = msg; }
}
